### ISSUE TITLE
Documents thumbnails

### ISSUE THREAD

**Issue by jonathanasquier** [softmonkeyjapan/angular-google-picker#14]
Hi,
I wondered if it was possible to get thumbnails (especially for photos/videos) from Drive in the array of documents? Am I missing parameters?

Thanks a lot for your work,

Jonathan

**Comment by softmonkeyjapan** [comment]
Hi,
Sorry for my late reply. I believe you'll have to make a request for each of your file within the `onPicked` callback : 

```js
$scope.onPicked = function (docs) {
  angular.forEach(docs, function (file, index) {
    $scope.files.push(file);

    var request = gapi.client.drive.files.get({ fileId: file.id });
    request.execute(function (fileMeta) {
      file.thumbnailLink = fileMeta.thumbnailLink;
    });
  });
}
```

In this context, `fileMeta` will have a complete list of information related to each of your files, including the thumbnail url (`thumbnailLink`).

**Comment by jonathanasquier** [comment]
Thanks, I believe the thumbnail link sent by gapi.client.drive.files does not have an expiration time?
