### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by bhavikmulia-searce** [softmonkeyjapan/angular-google-picker#16]
When i tried to upload files it's return an error "Server Rejected".

Also getting two errors in console.
1) Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://docs.google.com') does not match the recipient window's origin ('http://localhost:13080').(anonymous function) @ cb=gapi.loaded_0:77

2) Invalid 'X-Frame-Options' header encountered when loading 'https://docs.google.com/picker?protocol=gadgets&origin=http%3A%2F%2Flocalho…%3Atrue%7D))&rpctoken=tic259j42wgf&rpcService=c36g0mksuysk&thirdParty=true': 'ALLOW-FROM http://localhost:13080' is not a recognized directive. The header will be ignored.

Give me a solution for that.

Many thanks,
Bhavik Mulia

**Comment by softmonkeyjapan** [comment]
Hi,
About the errors (1 and 2), this is a Google problem. Here is a link to the related issue : #1.

About the `Server Rejected` error, please could you be more specific on how you've setup the directive and how you use it? Also, which browser are you using? I've tried, but could not reproduce such a scenario.

**Comment by bhavikmulia-searce** [comment]
It was a authorisation issue and now it's working fine......

Thanks for quick reply

**Comment by softmonkeyjapan** [comment]
Glad you made it work!
