### ISSUE TITLE
Want to upload a files as well as folders?

### ISSUE THREAD

**Issue by bhavikmulia-searce** [softmonkeyjapan/angular-google-picker#18]
Hi,

can you please let me know how i upload a whole folder like drive?

I have one requirement for upload a multiple folders?

Thanks,

**Comment by softmonkeyjapan** [comment]
Hi,

In order to select a folder, you could use the `setSelectFolderEnabled` from `DocsView` class : 

```javascript
lkGoogleSettingsProvider.views = [
  'DocsView().setIncludeFolders(true)',
  'DocsView(google.picker.ViewId.FOLDERS).setSelectFolderEnabled(true)'
];
```

This will make folders selectable. As for now, the directive will return the selected folder id. You can then use it to retrieve internal items. When I got a chance, I will digg into a solution allowing to easily get a folder and it's content recursively. Of course, everyone is welcome to make a pull request.

Cheers.

**Comment by bhavikmulia-searce** [comment]
Hi,

Thanks for replying but When we try to upload a folder using the "Upload", it just lists the files residing in the folder. But what we want is we want the same hierarchy structure to be uploaded. Is that possible ?

**Comment by softmonkeyjapan** [comment]
It is possible using Google Picker API. However, the directive does not currently support it. As for now, you'll have to roll your own solution to handle that case.
As I think it could be a nice feature to have, I would try to come with a nice implementation to allow it (probably another plugin).

**Comment by bhavikmulia-searce** [comment]
Hello,

When i click on icon for opening the google picker it's return an error like
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://docs.google.com') does not match the recipient window's origin ('http://localhost:13080').(anonymous function) @ cb=gapi.loaded_0:76
about:blank:1 Invalid 'X-Frame-Options' header encountered when loading 'https://docs.google.com/picker?protocol=gadgets&origin=http%3A%2F%2Flocalho…%3Atrue%7D))&rpctoken=dkwc0nsh1ygz&rpcService=rxwko1sk9iga&thirdParty=true': 'ALLOW-FROM http://localhost:13080' is not a recognized directive. The header will be ignored.

Invalid 'X-Frame-Options' header encountered when loading 'https://docs.google.com/picker?protocol=gadgets&origin=http%3A%2F%2Flocalho…%3Atrue%7D))&rpctoken=dkwc0nsh1ygz&rpcService=rxwko1sk9iga&thirdParty=true': 'ALLOW-FROM http://localhost:13080' is not a recognized directive. The header will be ignored.

And When i click on upload nothing performed.
So, can you please look in to it and give me reply ASAP because it's a live project.

Thanks in advance....

**Comment by bhavikmulia-searce** [comment]
And we tried using your demo picker but it's also return same response an error

**Comment by softmonkeyjapan** [comment]
Hey, about the console errors, I believe we already talked about that here #16. As for the second error : 
```
Uncaught CustomError: Error in protected function: Cannot read property 'call' of undefinedb @ 2344684216-picker_modularized_i18n_opc.js:367
```
I cannot reproduce it. However, the reason why the picker is not returning anything is because the code recently changed (v0.2.2) to support ES6 feature. Inside your HTML, you'll need to replace this line : 
```html
<a href="javascript:;" lk-google-picker on-picked="onPicked()">Pick a file</a>
```
by this line : 
```html
<a href="javascript:;" lk-google-picker on-picked="onPicked(docs)">Pick a file</a>
```

Passing `docs` to `onPicked` method should make it work again. The reason for this has been describe within this pull request #17

**Comment by bhavikmulia-searce** [comment]
Thanks for quick response. ☺

On Sat, Oct 17, 2015 at 1:32 AM, Loïc KARTONO <notifications@github.com>
wrote:

> Hey, about the console errors, I believe we already talked about that here
> #16 <https://github.com/softmonkeyjapan/angular-google-picker/issues/16>.
> As for the second error :
>
> Uncaught CustomError: Error in protected function: Cannot read property 'call' of undefinedb @ 2344684216-picker_modularized_i18n_opc.js:367
>
> I cannot reproduce it. However, the reason why the picker is not returning
> anything is because the code recently changed (v0.2.2) to support ES6
> feature. Inside your HTML, you'll need to replace this line :
>
> <a href="javascript:;" lk-google-picker on-picked="onPicked()">Pick a file</a>
>
> by this line :
>
> <a href="javascript:;" lk-google-picker on-picked="onPicked(docs)">Pick a file</a>
>
> Passing docs to onPicked method should make it work again. The reason for
> this has been describe within this pull request #17
> <https://github.com/softmonkeyjapan/angular-google-picker/pull/17>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/softmonkeyjapan/angular-google-picker/issues/18#issuecomment-148820270>
> .
>



-- 

Bhavik Mulia  |  IT Analyst

[image: Description: Inline image 2]


DID +91 2816193800 | Extn. 6855

CELL +91 7878048480

Searce <http://www.searce.com/>  |  We identify better ways of doing things.
