### ISSUE TITLE
Not able to add views

### ISSUE THREAD

**Issue by geojacobm6** [softmonkeyjapan/angular-google-picker#2]
I want to fetch only documents and presentations from google drive, so when i try to rewrite  views, i got the following error `lkGoogleSettingsProvider.views is not a function`, Will you please help me to fix this?

``` js
var googlepickerController = angular.module('googlepickerControllers', ['lk-google-picker'])

googlepickerController.config(['lkGoogleSettingsProvider', function(lkGoogleSettingsProvider) {
    // Configure the API credentials here
    lkGoogleSettingsProvider.configure({
        apiKey   : '*****************************',
        clientId : '*************************************************',
        views    : ['DocsView()'],
    });
}])
```

**Comment by tomrainedotcom** [comment]
This controller is great, I do have one question about the views though... I'm not sure how you go about making the DocsView only show the ViewId.DOCS_IMAGES. I have tried lkGoogleSettingsProvider.views = ['DocsView(ViewId.DOCS_IMAGES)']; and lkGoogleSettingsProvider.views = ['DocsView(DOCS_IMAGES)']; and I get ReferenceError: ViewId is not defined and ReferenceError: DOCS_IMAGES is not defined respectively... any ideas would be a great help.

**Comment by softmonkeyjapan** [comment]
@tomrainedotcom you need to use the `google.picker` namespace : 

```js
lkGoogleSettingsProvider.views = ['DocsView(google.picker.ViewId.DOCS_IMAGES)'];
```

**Comment by tomrainedotcom** [comment]
@softmonkeyjapan thanks champ. Absolute legend.
