### ISSUE TITLE
Demo Not working

### ISSUE THREAD

**Issue by shashwatbhatt** [softmonkeyjapan/angular-google-picker#21]
400. That’s an error.

Error: origin_mismatch

Application: Angular Google Drive Picker Demo

You can email the developer of this application at: kartono.loic@gmail.com

Request Details
proxy=oauth2relay672633426
immediate=false
scope=https://www.googleapis.com/auth/drive
origin=https://softmonkeyjapan.github.io
response_type=token
redirect_uri=postmessage
state=848035323|0.1860715458
client_id=20787361493-372fi66o31k7t4t2ha3nvj5j36blm417.apps.googleusercontent.com
include_granted_scopes=true
That’s all we know.

**Comment by softmonkeyjapan** [comment]
Thanks for your feedback. I just tried the demo at http://softmonkeyjapan.github.io/angular-google-picker/ and I don't see any issue, it works as expected. Do you have any plugin or cache that could mess with the request? Thanks

**Comment by shashwatbhatt** [comment]
Thanks for your prompt reply I just tried the demo and It it worked as expected. You are right I cleared my cache and cookies and It started working Thanks
