### ISSUE TITLE
Syntax error in Readme

### ISSUE THREAD

**Issue by leitasat** [softmonkeyjapan/angular-google-picker#22]
Minor thing but might be annoying. Tried to create a PR, but don't have permissions apparently.

> The variable `data` is not defined. Google returns a plain array now, so we are good to go with `docs`.

```javascript
diff --git a/README.md b/README.md
index 12df294..b617cfc 100644
--- a/README.md
+++ b/README.md
@@ -59,7 +59,7 @@ Download [https://github.com/softmonkeyjapan/angular-google-picker/archive/0.2.2
      }
 
      $scope.onPicked = function (docs) {
-       angular.forEach(data.docs, function (file, index) {
+       angular.forEach(docs, function (file, index) {
          $scope.files.push(file);
        });
      }
```

**Comment by softmonkeyjapan** [comment]
Thanks for your feedback. Indeed, there is a mistake in the README. You don't have permission to change the README directly. Please, fork the repo and make a pull request from your fork. I'll merge it afterwards.
