### ISSUE TITLE
Origin mismatch in demo

### ISSUE THREAD

**Issue by robin-thoni** [softmonkeyjapan/angular-google-picker#26]
Hi,

You got an error on your demo page (https://softmonkeyjapan.github.io/angular-google-picker/) when clicking on pick file:

![selection_004](https://cloud.githubusercontent.com/assets/9640353/15628157/990dfdf4-24fa-11e6-80cf-689a8dbb54f8.png)

**Comment by softmonkeyjapan** [comment]
@robin-thoni Thanks for your feedbacks. The demo should be working again by now 👍
