### ISSUE TITLE
Google Picker on modal

### ISSUE THREAD

**Issue by vicki3z** [softmonkeyjapan/angular-google-picker#4]
I've tried using angular-google-picker on modal, but it didn't seems to work.
The picker went behind the modal and I can't choose files.

How to make this work on modal? 

P.S. I'm also using angular-ui bootstrap

**Comment by theanuraggupta** [comment]
I'm getting an empty box with the same error. Please help me.

![getting empty picker dialog box](https://user-images.githubusercontent.com/15166401/33229808-68b43abe-d1fc-11e7-9a4a-e729d351f721.PNG)

**Comment by sandeepdeore08** [comment]
I am getting error  with empty box of upload File ..

![image](https://user-images.githubusercontent.com/33985139/34903821-5e16cc18-f874-11e7-931b-178c57fbbfce.png)
