### ISSUE TITLE
Error on file select

### ISSUE THREAD

**Issue by vacarsu** [softmonkeyjapan/angular-google-picker#8]
Hi I'm getting an error in console using chrome when I select a file from drive.
Cannot read property 'push' of undefined.

on this line:
scope.pickerFiles.push(file);

**Comment by vacarsu** [comment]
My bad I had set my $scope variable to an empty object instead of an array by mistake. Silly me.

**Comment by softmonkeyjapan** [comment]
Hey, no problem. Glad you were able to make this works.
